In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("task2.csv")

In [3]:
df

ID Segment type Segment Description Answer        Count  \
0     292890.8970          web     Meridian, Idaho     No     0.000000   
1     292887.9870          web     Meridian, Idaho     No     0.000000   
2     292894.0656       gender     Meridian, Idaho     No   499.173606   
3     292887.1180          web     Meridian, Idaho     No     0.000000   
4     292893.6561       gender     Meridian, Idaho     No   455.925963   
...           ...          ...                 ...    ...          ...   
1891  292887.5496          web     Meridian, Idaho     No     0.000000   
1892  292881.6932       mobile     Meridian, Idaho     No  1203.190399   
1893  292900.8499       gender     Meridian, Idaho     No   806.378820   
1894  292893.8600       gender     Meridian, Idaho     No  1149.529381   
1895  292890.2944          web     Meridian, Idaho     No     0.000000   

      Percentage  It became a relationship  
0       0.000000                         0  
1       0.000000                         0  
2       0.225255                         0  
3       0.000000                         0  
4       0.211360                         0  
...          ...                       ...  
1891    0.000000                         0  
1892    0.312360                         0  
1893    0.488025                         0  
1894    0.488984                         0  
1895    0.000000                         0  

[1896 rows x 7 columns]

In [19]:
df["Answer"].replace({"I don't use Tinder":"No"},inplace=True)

In [33]:
df["Answer"].replace({"No":0,"Yes":1},inplace=True)

In [4]:
import numpy as np

In [5]:
df.isnull()

ID  Segment type  Segment Description  Answer  Count  Percentage  \
0     False         False                False   False  False       False   
1     False         False                False   False  False       False   
2     False         False                False   False  False       False   
3     False         False                False   False  False       False   
4     False         False                False   False  False       False   
...     ...           ...                  ...     ...    ...         ...   
1891  False         False                False   False  False       False   
1892  False         False                False   False  False       False   
1893  False         False                False   False  False       False   
1894  False         False                False   False  False       False   
1895  False         False                False   False  False       False   

      It became a relationship  
0                        False  
1                        False  
2                        False  
3                        False  
4                        False  
...                        ...  
1891                     False  
1892                     False  
1893                     False  
1894                     False  
1895                     False  

[1896 rows x 7 columns]

In [6]:
df.isnull().sum()

ID                          0
Segment type                0
Segment Description         0
Answer                      0
Count                       0
Percentage                  0
It became a relationship    0
dtype: int64

In [7]:
import matplotlib.pyplot as plt
from sklearn import linear_model

In [8]:
from sklearn.model_selection import train_test_split

In [35]:
y=df["It became a relationship"]

In [10]:
y

0       0
1       0
2       0
3       0
4       0
       ..
1891    0
1892    0
1893    0
1894    0
1895    0
Name: It became a relationship, Length: 1896, dtype: int64

In [43]:
x=df.drop(["It became a relationship","Segment Description", "Segment type", "ID"], axis=1)

In [44]:
x

Answer        Count  Percentage
0          0     0.000000    0.000000
1          0     0.000000    0.000000
2          0   499.173606    0.225255
3          0     0.000000    0.000000
4          0   455.925963    0.211360
...      ...          ...         ...
1891       0     0.000000    0.000000
1892       0  1203.190399    0.312360
1893       0   806.378820    0.488025
1894       0  1149.529381    0.488984
1895       0     0.000000    0.000000

[1896 rows x 3 columns]

In [45]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.15, random_state=42)

In [46]:
x_train

Answer        Count  Percentage
185        0   476.626020    0.223724
575        0     0.000000    0.000000
1821       0     1.000000    0.500000
478        0     0.000000    0.000000
1477       0     0.000000    0.000000
...      ...          ...         ...
1130       0   534.497205    0.297141
1294       0   963.338965    0.505186
860        0     0.000000    0.000000
1459       0  1061.604943    0.302600
1126       0   509.972995    0.301028

[1611 rows x 3 columns]

In [15]:
y_train

185     0
575     0
1821    0
478     0
1477    0
       ..
1130    0
1294    0
860     0
1459    1
1126    0
Name: It became a relationship, Length: 1611, dtype: int64

In [47]:
x_test

Answer        Count  Percentage
1319       0     0.000000    0.000000
611        1     2.000000    0.133000
964        0  1066.134110    0.276810
1316       0   557.889127    0.274555
585        0     0.000000    0.000000
...      ...          ...         ...
1341       0   844.417862    0.452514
570        0     0.000000    0.000000
1169       0   532.760734    0.240402
1037       0     1.000000    0.200000
1578       0  1081.011003    0.518052

[285 rows x 3 columns]

In [17]:
y_test

1319    0
611     1
964     1
1316    0
585     0
       ..
1341    1
570     0
1169    0
1037    0
1578    0
Name: It became a relationship, Length: 285, dtype: int64

In [27]:
#let's 1st use logistic Regression

In [28]:
from sklearn.linear_model import LogisticRegression

In [30]:
model1 = LogisticRegression()

In [48]:
model1.fit(x_train, y_train)

LogisticRegression()

In [50]:
model1.predict(x_test)

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1],
      dtype=int64)

In [51]:
model1.score(x_test, y_test)

0.5543859649122806

In [52]:
model1.predict_proba(x_test)

array([[0.8497547 , 0.1502453 ],
       [0.49637758, 0.50362242],
       [0.60139028, 0.39860972],
       [0.66929371, 0.33070629],
       [0.8497547 , 0.1502453 ],
       [0.66567226, 0.33432774],
       [0.76497744, 0.23502256],
       [0.8497547 , 0.1502453 ],
       [0.68203071, 0.31796929],
       [0.51571842, 0.48428158],
       [0.8497547 , 0.1502453 ],
       [0.61046128, 0.38953872],
       [0.58056912, 0.41943088],
       [0.66514793, 0.33485207],
       [0.09438056, 0.90561944],
       [0.58759212, 0.41240788],
       [0.2758326 , 0.7241674 ],
       [0.67301164, 0.32698836],
       [0.72168663, 0.27831337],
       [0.67876604, 0.32123396],
       [0.33077323, 0.66922677],
       [0.8497547 , 0.1502453 ],
       [0.8497547 , 0.1502453 ],
       [0.8497547 , 0.1502453 ],
       [0.51053822, 0.48946178],
       [0.6753526 , 0.3246474 ],
       [0.58209846, 0.41790154],
       [0.8497547 , 0.1502453 ],
       [0.8497547 , 0.1502453 ],
       [0.8497547 , 0.1502453 ],
       [0.

In [53]:
#let's now use linear regression

In [54]:
model2=linear_model.LinearRegression()

In [55]:
model2.fit(x_train, y_train)

LinearRegression()

In [56]:
model2.predict(x_test)

array([0.13110622, 0.50854578, 0.40307909, 0.34747717, 0.13110622,
       0.34679671, 0.25246016, 0.13110622, 0.33658025, 0.48467328,
       0.13110622, 0.39526025, 0.4224553 , 0.34731559, 1.00343141,
       0.41566468, 0.71796861, 0.33915883, 0.29636847, 0.33781561,
       0.66058016, 0.13110622, 0.13110622, 0.13110622, 0.48932075,
       0.34116537, 0.43239894, 0.13110622, 0.13110622, 0.13110622,
       0.32273277, 0.13110622, 0.34595904, 0.35766453, 0.39487952,
       0.32826209, 0.4051513 , 0.38164705, 0.16015829, 0.34408753,
       0.42286945, 0.57523721, 0.30663482, 0.13110622, 0.57534407,
       0.13110622, 0.13110622, 0.45371563, 0.13110622, 0.67764663,
       0.13110622, 0.44063289, 0.49756318, 0.62019344, 0.31557934,
       0.49166427, 0.29947359, 0.33677724, 0.13110622, 0.13110622,
       0.13110622, 0.13110622, 0.13110622, 0.42498746, 0.35456701,
       0.13110622, 0.43196364, 0.37821952, 0.13110622, 0.44424059,
       0.13110622, 0.13110622, 0.49598542, 0.13110622, 0.49057

In [57]:
model2.predict(x_test).round()

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [58]:
model2.score(x_test, y_test)

0.11284305501232161

In [63]:
x=df.drop(["It became a relationship","Segment Description", "Segment type", "ID"], axis=1)

In [64]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.15, random_state=42)

In [66]:
from sklearn import svm, datasets
model = svm.SVC(kernel='rbf', C=30, gamma='auto')
model.fit(x_train, y_train)
model.score(x_test, y_test)

0.8280701754385965

In [72]:
from sklearn import svm, datasets
model = svm.SVC(kernel='rbf', C=20, gamma='auto')
model.fit(x_train, y_train)
model.score(x_test, y_test)

0.8245614035087719

In [73]:
from sklearn import svm, datasets
model = svm.SVC(kernel='rbf', C=10, gamma='auto')
model.fit(x_train, y_train)
model.score(x_test, y_test)

0.8070175438596491

In [74]:
from sklearn import svm, datasets
model = svm.SVC(kernel='rbf', C=1, gamma='auto')
model.fit(x_train, y_train)
model.score(x_test, y_test)

0.8035087719298246

In [75]:
from sklearn import svm, datasets
model = svm.SVC(kernel='rbf', C=50, gamma='auto')
model.fit(x_train, y_train)
model.score(x_test, y_test)

0.8385964912280702

In [76]:
from sklearn import svm, datasets
model = svm.SVC(kernel='rbf', C=100, gamma='auto')
model.fit(x_train, y_train)
model.score(x_test, y_test)

0.8526315789473684

In [77]:
from sklearn import svm, datasets
model = svm.SVC(kernel='rbf', C=500, gamma='auto')
model.fit(x_train, y_train)
model.score(x_test, y_test)

0.8526315789473684

In [78]:
from sklearn import svm, datasets
model = svm.SVC(kernel='rbf', C=1000, gamma='auto')
model.fit(x_train, y_train)
model.score(x_test, y_test)

0.8456140350877193